### ISSUE TITLE
Add support for timeout for AwaitableUnaryClientCallListener.onClose

### ISSUE THREAD

**Issue by sergeymeshkov** [openzipkin/zipkin-reporter-java#137]
We user Stackdriver Trace and spring-cloud-gcp-starter-trace library. Under high server load, Zipkin throws an error while waiting for server response. 
By default AwaitableUnaryClientCallListener timeout 5000 ms and this value can't be changed. Is it possible to add this configuration? 

Exception:
```
Exception in thread "AsyncReporter{StackdriverSender{PROJECT_ID}}" java.lang.IllegalStateException: timeout waiting for onClose. timeoutMs=5000, resultSet=false 
at zipkin2.reporter.stackdriver.internal.AwaitableUnaryClientCallListener.await(AwaitableUnaryClientCallListener.java:45)
at zipkin2.reporter.stackdriver.internal.UnaryClientCall.doExecute(UnaryClientCall.java:46) 
at zipkin2.Call$Base.execute(Call.java:379) 
at zipkin2.Call$Mapping.doExecute(Call.java:237) 
at zipkin2.Call$Base.execute(Call.java:379) 
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:286) 
at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190)
```

**Comment by sergeymeshkov** [comment]
My apologies, I accidentally created an issue in the wrong repository.

**Comment by ewirch** [comment]
For the reference: here's the issue in the "correct" repository: https://github.com/openzipkin/zipkin-gcp/issues/121
