### ISSUE TITLE
LibthriftSender Read timed out

### ISSUE THREAD

**Issue by tomgithub2016** [openzipkin/zipkin-reporter-java#34]
I was testing using the thrift protocol  `LibthriftSender` to send span to Zipkin `ScribeCollector`
But   The client is always  running error`  org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out`

first : `java -DSTORAGE_TYPE=mem  -jar  zipkin-server-1.20.1-exec.jar`
Zipkin server :
`2017-03-08 16:39:45.070  INFO 52972 --- [           main] c.f.nifty.core.NettyServerTransport      : started transport thrift:9410`

 9410 is ready

In Client   

```
 LibthriftSender thriftSender = LibthriftSender.create("127.0.0.1");
		  AsyncReporter reporter = AsyncReporter.builder(thriftSender)
                .build();
 		Tracer tracer = Tracer.newBuilder().localServiceName("xxxxx@Micro Service A").reporter(reporter).build();

		return tracer;
```

But Using the failure  in client  always run

```
 org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:380) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:230) ~[libthrift-0.9.3.jar:0.9.3]
	at zipkin.reporter.libthrift.InternalScribeCodec.readLogResponse(InternalScribeCodec.java:59) ~[classes/:na]
	at zipkin.reporter.libthrift.ScribeClient.log(ScribeClient.java:56) ~[classes/:na]
	at zipkin.reporter.libthrift.LibthriftSender.sendSpans(LibthriftSender.java:101) ~[classes/:na]
	at zipkin.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:228) [zipkin-reporter-0.6.12.jar:na]
	at zipkin.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:153) [zipkin-reporter-0.6.12.jar:na]
	at zipkin.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source) [zipkin-reporter-0.6.12.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_121]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_121]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_121]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_121]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_121]
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127) ~[libthrift-0.9.3.jar:0.9.3]
	... 13 common frames omitted
```

**Comment by adriancole** [comment]
just in case, can you try a service name that doesn't have any special
characters in it? ex. loweralphanumeric-hyphen?

**Comment by tomgithub2016** [comment]
yes,  I  modify this serviceName of    `abc`  ，but  It is still an error read time out

I didn't change anything, how to use ，Availability and stability?
```
 LibthriftSender thriftSender = LibthriftSender.create("localhost");
		  AsyncReporter reporter = AsyncReporter.builder(thriftSender)
                .build();
 		Tracer tracer = Tracer.newBuilder().localServiceName("abc").reporter(reporter).build();
```

**Comment by adriancole** [comment]
maybe try this and see if you can repeat the failure? the brave demo can be
switched from http to thrift and if that fails similarly, then we can
troubleshoot (as we'd be using the same code, versions etc)

https://github.com/openzipkin/brave-webmvc-example

**Comment by kriloleg** [comment]
Hi, @adriancole. Maybe this will be helpful.
I also saw this type of error. I'm using tracing in akka system where are generated a lot of messages and when I have near 250k messages then I see this error too.

**Comment by adriancole** [comment]
Hey, Oleg.

Are you using thrift/scribe because that is an existing tech at your site?
Or is it because the library you are using doesnt support anything else?
I'm a bit concerned with doing much on libthrift as it isnt very
sophisticated wrt error handling vs other thrift libs, and scribe itself is
an archived tech..

**Comment by kriloleg** [comment]
@adriancole, while writing tracing module for application I decided to compare performance impact of thrift/scribe and kafka and faced with this issue. On high load logs were full with SocketException.
We are not planning to use it in prod, but still it was important for us to know the difference.

**Comment by adriancole** [comment]
fyi reporter v2 drops the scribe transport
