### ISSUE TITLE
Warning on leaked connections to Zipkin with OkHttp

### ISSUE THREAD

**Issue by ivantopo** [openzipkin/zipkin-reporter-java#89]
On of our users found this in his logs:

```
[warn] o.OkHttpClient - A connection to http://localhost:9411/ was leaked. Did you forget to close a response body?
java.lang.Throwable: response.body().close()
    at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:143)
    at okhttp3.RealCall.captureCallStackTrace(RealCall.java:78)
    at okhttp3.RealCall.execute(RealCall.java:66)
    at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:35)
    at zipkin2.reporter.okhttp3.HttpCall.execute(HttpCall.java:26)
    at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:272)
    at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:179)
```

@adriancole already did a some initial research on what is happening here: https://gitter.im/openzipkin/zipkin?at=5a4e27ea97cedeb0482d9b34

**Comment by adriancole** [comment]
oops meant to raise a PR, but whatev https://github.com/openzipkin/zipkin-reporter-java/commit/dee684e9db8be8ab91e73ec6c2953ce8628044d6

**Comment by adriancole** [comment]
will cut a patch on master green
