### ISSUE TITLE
Can someone take a look at the odd issue

### ISSUE THREAD

**Issue by jgolubenko** [openzipkin/zipkin-reporter-java#93]
I cannot get this to work, I get 400 error from the zipkin server using the very simple code below

```
        Span span0 = null;

        try
        {
          span0 = zipkinTracer.buildSpan("SomeOperationName").
              asChildOf(zipkinTracer.extract(Format.Builtin.HTTP_HEADERS, new TextMapExtractAdapter(getTraceSpanMap(request))))
              .withTag("description", "Some Description").startManual();
        }
        finally
        {
          if(span0 != null)
            span0.finish();
        }
```

However I get only exception and nothing reported:

```Jan 08, 2018 1:13:20 PM zipkin.reporter.AsyncReporter$BoundedAsyncReporter$1 onError
WARNING: Dropped 1 spans due to IllegalStateException(response failed: Response{protocol=http/1.1, code=400, message=, url=http://xxx.server.com:9411/api/v2/spans})
java.lang.IllegalStateException: response failed: Response{protocol=http/1.1, code=400, message=, url=http://xxx.server.com:9411/api/v2/spans}
	at zipkin.reporter.okhttp3.OkHttpSender$CallbackAdapter.onResponse(OkHttpSender.java:262)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Zipkin Trace configured as bean with following code:
```
@Bean
  public io.opentracing.Tracer zipkinTracer()
  {
    OkHttpSender okHttpSender = OkHttpSender.create("http://xxx.server.com:9411/api/v2/spans");
    AsyncReporter<Span> reporter = AsyncReporter.builder(okHttpSender).queuedMaxSpans(1).build();
    Tracing braveTracer = Tracing.newBuilder().localServiceName("local-service-name-here").reporter(reporter).build();
    return BraveTracer.create(braveTracer);
  }
```

Zipkin (v2.3.1) server is started with following command:
```
docker run --rm -it -e "QUERY_LOG_LEVEL=DEBUG" -e "HOSTNAME=xxx.server.com" -e "logging.level.com.facebook.swift.service.ThriftServiceProcessor=INFO" -p 9411:9411 openzipkin/zipkin
```

**Comment by adriancole** [comment]
Use Tracing.Builder.spanReporter (the v2 one) not reporter (the v1 one)

You send v1 json to the v2 endpoint.

**Comment by jgolubenko** [comment]
@adriancole Thank you, that worked!
