### ISSUE TITLE
ByteBoundedQueue.offer should have a timeout

### ISSUE THREAD

**Issue by ankitkurani** [openzipkin/zipkin-reporter-java#97]
We are using HTTP reporter for zipkin with our application and we see all threads blocked waiting for ByteBoundedQueue.offer to be unlocked. While there is one thead which is trying to drain from the buffer, this goes on for few min as times. This happens often when the zipkin server becomes unavailable.

I took few dumps thread dumps, here is what I see:
Threads draining spans:
0x6206 
runnable 
-[0x00007ff6b9f69000]
java.lang.Thread.State: RUNNABLE
at zipkin2.reporter.ByteBoundedQueue.doDrain(ByteBoundedQueue.java:114)
at zipkin2.reporter.ByteBoundedQueue.drainTo(ByteBoundedQueue.java:85)
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:238)
at zipkin2.reporter.AsyncReporter$Builder.lambda$build$0(AsyncReporter.java:178)
at zipkin2.reporter.AsyncReporter$Builder$$Lambda$1.run(Unknown Source)
at java.lang.Thread.run(Thread.java:748)

While threads waiting for ByteBoundArray lock:
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
at zipkin2.reporter.ByteBoundedQueue.offer(ByteBoundedQueue.java:54)
at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.report(AsyncReporter.java:226)
at brave.internal.recorder.MutableSpanMap.reportOrphanedSpans(MutableSpanMap.java:82)
at brave.internal.recorder.MutableSpanMap.get(MutableSpanMap.java:52)
at brave.internal.recorder.MutableSpanMap.getOrCreate(MutableSpanMap.java:57)
at brave.internal.recorder.Recorder.tag(Recorder.java:73)

--

**Comment by adriancole** [comment]
can you update to latest zipkin-reporter? what's done under lock has been significantly changed due to this problem.

**Comment by ankitkurani** [comment]
I will try the latest reporter, but I don't see significant difference in this specific flow that will help with the problem I am seeing. There are still cases where the offer method could potentially block waiting for drain to release the lock

**Comment by adriancole** [comment]
the significant thing is that message encoding doesn't happen in this lock (which can be microseconds). anyway please report back if it is still an issue. we can re-open
